### PR TITLE
Fix crash

### LINKED ISSUE #36: tms&fns&tdfs crash when send request by python
tms&fns&tdfs crash when send request by python3 script

mesatee: b78ae148ad348fb3733f31fc4a7429adf56375bd
os: ubuntu-18.04 LTS
sgxsdk: v2.6.100.51363
rust:
    nightly-2019-08-01-x86_64-unknown-linux-gnu (default)
    rustc 1.38.0-nightly (8a58268b5 2019-07-31)
python: v3.6.8

for fns:
image-fns

for tdfs:
image-tdfs

for tms:
image-tms

script:
python

script file:
[crash.zip](https://github.com/mesalock-linux/mesatee/files/3705503/crash.zip)

### PR DESCRIPTION
**Pull request by litongxin1991**
## Description

Services will crash if the message size is too large.  Check message size before allocating buffer. 
Use build.toml to configure the max message size. 

Fixes #36 

## Type of change (select applied and DELETE the others)

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Use script provided in issue #36 to verify the patch.

## Checklist (check ALL before submitting PR, even not applicable)

- [X] Fork the repo and create your branch from `master`.
- [X] If you've added code that should be tested, add tests.
- [X] If you've changed APIs, update the documentation.
- [X] Ensure the tests pass (see CI results).
- [X] Make sure your code lints/format.

### CODE REVIEW

File: mesatee_config/config_gen/src/main.rs [hunk 1]
```diff
@@ -126,6 +136,7 @@ fn get_string<P: AsRef<Path>>(
 ) -> Result<String, ExitFailure> {
     match config_value {
         ConfigValue::Simple(ref s) => Ok(s.to_string()),
+        ConfigValue::Numerical(ref s) => Ok(s.to_string()),
```
Comment (m4sterchain) [inline mesatee_config/config_gen/src/main.rs]: Is the intended behavior Ok() or Err()?

Comment (litongxin1991) [reply mesatee_config/config_gen/src/main.rs]: I think Error is better. I'll fix it.

File: service.sh [hunk 2]
```diff
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-source ./environment
+source ./environment.deprecated
```
Comment (mssun) [inline service.sh]: `environment` is deprecated.
